// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_Exam.Models;

#nullable disable

namespace SDExam.Migrations
{
    [DbContext(typeof(MedicineContext))]
    partial class MedicineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD_Exam.Models.Medicine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Dose")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 100,
                            Description = "When headache",
                            Dose = 2.5,
                            Title = "Analgin"
                        },
                        new
                        {
                            ID = 2,
                            Amount = 200,
                            Description = "Good for blood",
                            Dose = 5.0,
                            Title = "Varfaryn"
                        },
                        new
                        {
                            ID = 3,
                            Amount = 50,
                            Description = "When cold",
                            Dose = 0.10000000000000001,
                            Title = "Nurofen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
